### ISSUE TITLE
[BUG] Enphase Envoy could not set up since version 0.8.12

### ISSUE THREAD

**Issue by rogervdh** [vincentwolsink/home_assistant_enphase_envoy_installer#331]
**Describe the bug**
Enphase Envoy (Installer) integration won't start anymore since version version 0.8.12 (updated from version 0.8.10). Please see error logs below

**Account type**
- [ ] Installer
- [X] DIY / DHZ
- [ ] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
- [ ] Metered with CTs installed
- [X] Metered without CTs
- [ ] Standard

- FW version: D8.3.5422
- Amount of micro inverters connected: 22

**Home Assistant**
- Version: 2026.6.4
- Home Assistant OS 18.1

Relevant snippet of Home Assistant error log. 

Logger: homeassistant.setup
Source: setup.py:341
First occurred: 4:01:45 PM (1 occurrence)
Last logged: 4:01:45 PM

Setup failed for custom integration 'enphase_envoy': Unable to import component: cannot import name 'JSONPath' from 'jsonpath' (/usr/local/lib/python3.14/site-packages/jsonpath.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1022, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1082, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/enphase_envoy/__init__.py", line 12, in <module>
    from .envoy_reader import EnvoyReader, StreamData
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 14, in <module>
    from jsonpath import JSONPath
ImportError: cannot import name 'JSONPath' from 'jsonpath' (/usr/local/lib/python3.14/site-packages/jsonpath.py). Did you mean: 'jsonpath'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1042, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1082, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/enphase_envoy/__init__.py", line 12, in <module>
    from .envoy_reader import EnvoyReader, StreamData
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 14, in <module>
    from jsonpath import JSONPath
ImportError: cannot import name 'JSONPath' from 'jsonpath' (/usr/local/lib/python3.14/site-packages/jsonpath.py). Did you mean: 'jsonpath'?

------------------------------------------------------------------------

Logger: homeassistant.util.loop
Source: util/loop.py:75
First occurred: 4:01:45 PM (2 occurrences)
Last logged: 4:02:08 PM

Detected blocking call to import_module with args ('custom_components.enphase_envoy',) in /usr/src/homeassistant/homeassistant/loader.py, line 1082: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 203, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2057, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1082, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
Detected blocking call to import_module with args ('custom_components.enphase_envoy.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1312: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 203, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2057, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 109, in sem_task return await task File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1521, in async_init flow, result = await self._async_init(flow_id, handler, context, data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1574, in _async_init flow = await self.async_create_flow(handler, context=context, data=data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1822, in async_create_flow handler = await _async_get_flow_handler( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4151, in _async_get_flow_handler await _load_integration(hass, domain, hass_config) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4130, in _load_integration await integration.async_get_platform("config_flow") File "/usr/src/homeassistant/homeassistant/loader.py", line 1115, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1105, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1280, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1312, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")

------------------------------------------------------------------------

Logger: custom_components.enphase_envoy
Source: config_entries.py:4132
Integration: Enphase Envoy (Installer) ([documentation](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/), [issues](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/issues))
First occurred: 4:02:08 PM (6 occurrences)
Last logged: 4:13:06 PM

Error occurred loading flow for integration enphase_envoy: cannot import name 'JSONPath' from 'jsonpath' (/usr/local/lib/python3.14/site-packages/jsonpath.py)

**Comment by vincentwolsink** [comment]
We had to switch to a different jsonpath library because the next version of Home Assistant uses a conflicting one.

It seems for you it still imports the old jsonpath library. How are you running Home Assistant, via HAOS or a different way?

**Comment by rogervdh** [comment]
I'm running Home Assistant OS 18.1 (just released today).

<img width="573" height="317" alt="Image" src="https://github.com/user-attachments/assets/86ed131d-d2a2-4f3b-8e6e-d04ae4e85250" />

**Comment by vincentwolsink** [comment]
There are a few options here:
1. Downgrade to an older version of the integration for now.
2. Update HA to the latest 2026.7 beta already. 
3. Wait until they release HA 2026.7.0 in a few days.

**Comment by rogervdh** [comment]
Perfect, since they're releasing 2026.7.0 tonight, I'll wait a few hours. Thanks for your swift response Vincent, really happy with the integration.

**Comment by Theetjuh** [comment]
Would love to know if that fixes it, will wait for the upgrade for now :)
Thanks in advance @vincentwolsink

**Comment by Kaaf76** [comment]
I think I had the same problem after the update of today. I tried to downgrade it to 0.8.10 en 0.8.8. Still unresponsive. After a reupgrade to 0.8.12 it started to work. Don't know why, but I'm happy now (same HA OS version as rogervdh)

**Comment by thbrd** [comment]
> I think I had the same problem after the update of today. I tried to downgrade it to 0.8.10 en 0.8.8. Still unresponsive. After a reupgrade to 0.8.12 it started to work. Don't know why, but I'm happy now (same HA OS version as rogervdh)

This method also fixed it for me.

**Comment by jeroenribbink** [comment]
My rest sensors are not starting due to version 0.8.12. I rolled back to 0.8.11 and it’s fine. 
It yelled in the HA logging about “jsonpath“ faults. 
In 0.8.12 I see just that change to “jsonpath-python”. But why does it affect other python code?

**Comment by rogervdh** [comment]
Just installed core 2026.7.0 and version 0.8.12 is working perfectly.

**Comment by titis14** [comment]
> My rest sensors are not starting due to version 0.8.12. I rolled back to 0.8.11 and it’s fine. It yelled in the HA logging about “jsonpath“ faults. In 0.8.12 I see just that change to “jsonpath-python”. But why does it affect other python code?

Hi,
Do you also have other plugins that stop working after you update?

I have the same problem with my solar router. If I update the Enphase Envoy Installer, I no longer get data from the sensors on my solar router. I did a rollback (thanks to Proxmox snapshots) and everything worked again. I re-updated just the Enphase Envoy Installer and I have the problem again, so it's definitely coming from the Enphase Envoy Installer.

It's also a Python script, and it shows this in the log.

Source: components/template/template_entity.py:99
Integration: Template (documentation, issues)
First occurred: 22:07:55 (17 occurrences)
Last recorded: 22:07:55
TemplateError('UndefinedError: list object has no element 2') while processing template 'Template<template=({% set cptVals =state_attr('sensor.msunpv_xml', 'cptVals')|replace(" ","") %} {{ (0 if cptVals.split(";")[2]|int(base=16)|int == 0 else ((0xFFFFFFFF - cptVals.split(";")[2]|int(base=16)) * -1)/10) |float }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.msunpv_enpv_j'
TemplateError('UndefinedError: list object has no element 3') while processing template 'Template<template=({% set cptVals =state_attr('sensor.msunpv_xml', 'cptVals')|replace(" ","") %}

**Comment by vincentwolsink** [comment]
Dependency management in Home Assistant is very tricky. Everything gets installed in the same python environment and potentially conflicts.

For the people with issues, I would hold off on updating this integration and first update HA to 2026.7.0 once it is available. After that update this integration.

**Comment by strati64** [comment]
> I think I had the same problem after the update of today. I tried to downgrade it to 0.8.10 en 0.8.8. Still unresponsive. After a reupgrade to 0.8.12 it started to work. Don't know why, but I'm happy now (same HA OS version as rogervdh)

I have upgrade this morning my hacs to 2026.7.0 (after 2026.6.4)
Same bug. And exactly Same fix (regress envoy 0.8.12 to 0.8.10 and New upgrade to 0.8.12)
No more plugin affected. Only envoy ! 
My system is haos on rspi4/arm64

Home Assistant OS Core 2026.7.0
Supervisor 2026.06.2
Operating System 18.1
Interface utilisateur 20260624.3
Application Companion 2026.6.5-full (22884)

**Comment by strati64** [comment]
> Dependency management in Home Assistant is very tricky. Everything gets installed in the same python environment and potentially conflicts.
> 
> For the people with issues, I would hold off on updating this integration and first update HA to 2026.7.0 once it is available. After that update this integration.

In my case, it was actually the update to 2026.7.0 that caused the problem. The plugin was already on version 0.8.12! 😅 

Python will always be a headache when it comes to these update! 😂

**Comment by eijlers** [comment]
After updating HA to 2026.7.0 I had the same problem. For me worked the following:
- Complete remove this integration (in HACS select the the integration >> triple point >> remove this integration)
- Remove integration (emphase_envoy) folder in custom_components folder (Just to be sure everything is gone)
- Restart HA
- You'll see the regular Envoy/Enphase pop-up
- Add this repo to HACS (again)
- Add Envoy Installer integration (0.8.12)
- Restarted HA
- Add the Envoy

Setup:
Standard HAOS on a N150. HA-OS 18.1, Core 2026.7, HA-Supervisor 2026.06.2, Companion app: 2026.6.0 (iPad)

**Comment by GlenGraif** [comment]
With a little help from Claude:

Update from someone who hit the mirror image of this, on 0.8.10 rather than 0.8.12.
Confirmed root cause: two unrelated PyPI distributions both install a top-level module literally called jsonpath:
	•	jsonpath (Phil Budne’s, currently 0.82.2), a flat module exposing a callable jsonpath(data, path) function.
	•	jsonpath-python (sean2077’s), a package exposing a JSONPath class, no bare callable function.
Which one you need depends on which version of this integration you run, because the import style changed between versions:
	•	0.8.10’s envoy_reader.py does from jsonpath import jsonpath (function style) and its manifest.json correctly requires jsonpath.
	•	0.8.12’s envoy_reader.py does from jsonpath import JSONPath (class style) and its manifest.json correctly requires jsonpath-python.
So each version’s manifest.json is internally consistent with its own code. The actual bug is that Home Assistant doesn’t uninstall a custom integration’s old pip requirements when you update (or downgrade) it. If you ever ran a version needing one of these two same-named packages and then move to a version needing the other, the old package’s files stick around on disk and collide with the new one, since both claim the same importable module name jsonpath.
That produces two different symptoms depending on which file wins on disk:
	•	ImportError: cannot import name 'JSONPath' from 'jsonpath' (reported here, 0.8.12, leftover Budne’s jsonpath blocking the needed jsonpath-python)
	•	TypeError: 'module' object is not callable (the variant I hit on 0.8.10, leftover jsonpath-python blocking the needed jsonpath)
Fix, whichever direction you’re in: figure out which package your currently-installed version’s manifest.json actually requires, then:

```

pip uninstall -y jsonpath jsonpath-python
pip install <the one your manifest.json requires>

```

followed by a full Home Assistant Core restart, not just an integration reload (Python caches the broken module in memory, so a reload alone won’t pick up the fix).
Worth flagging for the maintainer: since both packages claim the same importable module name, this will keep resurfacing for anyone who updates across the version where the import style changed, or if something else on the same HA instance pulls in the other one as a transitive dependency. Might be worth switching to a vendored/renamed import, or dropping the dependency altogether since only a single simple path lookup is being done here.

**Comment by Theetjuh** [comment]
no issues here, when on 2026.6.4 I updated the envoy installation, updated to 2026.7.1 and I don't see any errors.

**Comment by theelnino43** [comment]
> After updating HA to 2026.7.0 I had the same problem. For me worked the following:
> 
> * Complete remove this integration (in HACS select the the integration >> triple point >> remove this integration)
> * Remove integration (emphase_envoy) folder in custom_components folder (Just to be sure everything is gone)
> * Restart HA
> * You'll see the regular Envoy/Enphase pop-up
> * Add this repo to HACS (again)
> * Add Envoy Installer integration (0.8.12)
> * Restarted HA
> * Add the Envoy
> 
> Setup: Standard HAOS on a N150. HA-OS 18.1, Core 2026.7, HA-Supervisor 2026.06.2, Companion app: 2026.6.0 (iPad)

I tried this as well, and I got data for a minute, but now I'm back to "error communicating with API". Any ideas @vincentwolsink ?

I'm running core-2026.7.2 on Home Assistant OS.  Below the debug-log

2026-07-17 22:08:47.617 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Checking Token value: [GECENSUREERD_TOKEN]
2026-07-17 22:08:47.617 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Token is populated: [GECENSUREERD_TOKEN]
2026-07-17 22:08:47.617 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] TOKEN TYPE: installer
2026-07-17 22:08:47.618 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Token expired on: 2026-07-09 05:45:11
2026-07-17 22:08:47.618 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Found Expired token - Retrieving new token
2026-07-17 22:08:47.618 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetching Entrez token
2026-07-17 22:08:48.785 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Entrez Token: [GECENSUREERD_TOKEN]
2026-07-17 22:08:48.786 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] TOKEN TYPE: installer
2026-07-17 22:08:48.786 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Token expires at: 2026-07-18 10:08:48
2026-07-17 22:08:48.786 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP POST Attempt: https://[ENVOY_IP]/auth/check_jwt
2026-07-17 22:08:48.787 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP POST Data: None
2026-07-17 22:09:18.794 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] TransportError: 
2026-07-17 22:09:18.795 DEBUG (MainThread) [custom_components.enphase_envoy] Finished fetching envoy Envoy [ENVOY_SERIAL] data in 31.179 seconds (success: False)
2026-07-17 22:09:18.796 INFO (MainThread) [custom_components.enphase_envoy] Config entry 'Envoy [ENVOY_SERIAL]' for enphase_envoy integration not ready yet: Error communicating with API: ; Retrying in 10 seconds
2026-07-17 22:09:18.796 DEBUG (MainThread) [custom_components.enphase_envoy] Full exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  ... [TRACEBACK INGEKORT] ...
  File "/usr/local/lib/python3.14/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/enphase_envoy/__init__.py", line 102, in async_update_data
    await envoy_reader.get_data()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 1250, in get_data
    await self.init_authentication()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 1089, in init_authentication
    await self._get_enphase_token()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 1022, in _get_enphase_token
    await self._refresh_token_cookies()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 1033, in _refresh_token_cookies
    token_validation = await self._async_post(
                       ^^^^^^^^^^^^^^^^^^^^^^^
        ENDPOINT_URL_CHECK_JWT.format(self.host)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
  ... [TRACEBACK INGEKORT] ...
  File "/usr/local/lib/python3.14/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 435, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/enphase_envoy/__init__.py", line 106, in async_update_data
    raise UpdateFailed(f"Error communicating with API: {err}") from err
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/enphase_envoy/__init__.py", line 125, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in async_config_entry_first_refresh
    await self._async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 360, in _async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API:

**Comment by vincentwolsink** [comment]
@theelnino43 Your issue has nothing to do with the jsonpath library. Could you please move it to a new issue and tell me what the displayed ENVOY_IP is?
